steps:
  - name: 'node:22.11.0-alpine'
    args:
      - npm
      - ci

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv:
      - GOOGLE_SA
    args:
      - '-c'
      - |
        echo $${GOOGLE_SA} > GOOGLE_SA.json
        export GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_SA.json

  - name: 'cypress/browsers:node-22.11.0-chrome-131.0.6778.85-1-ff-132.0.2-edge-131.0.2903.70-1'
    env:
      - LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$BRANCH_NAME
    args:
      - '-c'
      - >-
        npm install -g @lhci/cli@0.14.x && lhci autorun --failOnUploadFailure
        --config=.github/workflows/lighthouse/lighthouserc.json
        --collect.staticDistDir=example --upload.target=filesystem 
        --upload.outputDir=. --upload.reportFilenamePattern=lighthouse-report.%%EXTENSION%%
    id: lighthouse
    entrypoint: /bin/sh

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'lighthouse-report.html', 'gs://${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html']

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    secretEnv:
      - GITHUB_TOKEN
    args:
      - '-c'
      - >-
        curl -X POST 
        -H "Authorization: token $(echo $${GITHUB_TOKEN} | tr -d '\n')" 
        -H "Accept: application/vnd.github.v3+json" 
        "https://api.github.com/repos/${_GITHUB_REPO}/issues/${_PR_NUMBER}/comments" 
        -d '{"body":"Report Lighthouse: https://storage.googleapis.com/${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html"}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


substitutions:
  _GITHUB_REPO: 'gregoriopalama/alt-attr-lighthouse-audit'

secrets:
  - kmsKeyName: projects/seetheunseen/locations/global/keyRings/github-secrets/cryptoKeys/github-token
    secretEnv:
      GITHUB_TOKEN: 'CiQA7FZl4ZEjQ6qEXCD/xfgtEylkLRGYnKF4WmyQ7cJ2nxu3cjcShwEAvHKVLf1YRrG8FklT9O1YMYetM7+BTC0aSuSphwqDiK6GYzKxzxClDSUnHHzJwU0xrRl/UzwvEH31PyQZCgyBMojxQeLO2KpTJy4otKZGK2DUbgxpCscEXwADWAtwMkkxwvwVjvHcFXoGLc7ZydbknXmIXvuqV2ScI/obJwqEmTqAM0PGhAI='
  - kmsKeyName: >-
      projects/seetheunseen/locations/global/keyRings/google-service-accounts/cryptoKeys/google-application-credentials
    secretEnv:
      GOOGLE_SA: >-
        CiQAbH9SZAlLXpLDuAFwJ7kDMYVz9tffT7ujyDD0Oh2AGHfAHJUSthIA1QN88G1y39s9gNnySjYD+8AhMIyfx1MBs73etKMQZUaecOak7AonG+u/eKxJswAZMkGZLohFEmMoYDJLFF0mWstKJWtw1VEo/glhiLnYGfF3bksvC0nYzWyj0NPKBabW5kvqWlNHuTw8adPtXYdnOejFzrli/SDlsXnvg2H9O4tt8zc3B3X/LXm5p3YoLfWln2eu19cWHyXtXm23YNJceM5NLSNrCV5Aaaqgl6cwvQFalSTtKgV1bYxLqaVyhXlVqSsBa4S2UIMroqa1iircmbfVSDAR49pOpx2lmCU2exANQOYy5g/vRn3X+j49d8eP9gPIFf+5fRgM6hCHD1cecIm+OEPXgW7/Wo1AA4dQFHHGPoAOQ+n6Pf7ydsOPCjrE2obAvtGUJEUW4Zee88EHwCIHM2ROw/+itPEZwiNkFbAB9uO0nO/lCJwOrxnD/BmePm/Wmo/lh6XNO4wkvA/RNj8mnnrkbmVbBuMhV9QoOF1u4XcSXOKJFoHtE3jWZ0YyeGGC2FsU3XUwGAj9hGaFtw28i7ndYji6KpuOO3p6t6nGsfdF8tlc5g4HUJ3Shy6N0LuGXdDSSHQqGhekCOcustMJjTH/WV957vD4aHxPzjueLd6+4YTWTk6zxT3YZPqkr8m0sqdJ6Ud19kgyJWoFhRCTQpj/gEUo+cEOD0WCKxxRKYvcRT3O4U0Y9c7e4g3gJb4QMX0icq4PnU473uCV5O2OhY4gxGy+tGn8vzZjI92Ms1iq1o7QNoMVTEZ1rADfBRq6u5hNcItl+b9EHCKMQSg6KKIHPYPLrynjaWo/YZygvvb4YL90u+/nlLnhztKL76hyUkCu3E3f4ksx7GHqKml1Wggu59fJ/6QPzlodzt9NuORyvlkHmyyu0JW7g7LYXEexI+huoYVFr4CDw7zLPdUkI9seSgodtvaezy8P3l+2byspLflIAF/m/2VWc2j32jjLoq3ZyDu4S5a4oneIV62u5fWEz6hv0jBqB+1c7QZ/e62ztEb1VF3bRvKRak66zHlecv+ETAMppBM0sigWY/9lh7dXWNUODm63PYiJ/pCuPd+iIVhQXj2Rs6BfXIi7+G2m+QTyr7d+HN90KFmd6V0fgsCD+fJ8QQxJx371ZwK0E584bL2dG+TfZMD8uCG9L93fDRwuSAmra84+qycslFw1hBjeWKOy8z7U60YFArNmU3oRp58pYuOXOTPeTxz0c3dwrQtkmCLETwoQUvyosLumvkCR+WhoYgD/x3VqX8a5Juh9STgTCnM+yvTtlmQ8AZZzC2l7SkVwaxbruw4m5mc6AlhxEy7hq7Hoeu+evMgj4cG5pTC57rFifcajVddhxIJ6P1tyhR0mHT2/GM5pfpeD5S3+hz5atFJZY1XIypJND6EwREOY/ErOKHkh4b7B6JXiVGVvgnDeoIR3CYo8569hDNweNz/R2JQ9D0m2AclLKw9m09G4R4jcNCe821vUlWqfT+TYzGNcw8wOX+a6Gthe/aqBqTA6IsY25jXmwnrldyEKucMnst4MZzQBFxWpoxF241MFlwYWHFkJgnEMe1llzHCkG9CwDjiKFrWqO020Zpz7hrmT8Pg+WSJ49E2a1o8DJVN7ZsIUwrkACgHoG6YR6LbCgvZdmC12sN3iqU6JQoUdz0MbMsWI40htwLRDYJv4OZSqd1f54vCoTuuzGtg7XdfQR7CLddT1/gt/ZYudF4pejSx41TQyZ6YBc97wcpVutsVv0mlWcYk8OV9OhgcO9wHNSkAle9vZ4uId3uqXXl/gHVRcFGImuIxxMFcI78mnsAti2Dv2VEx2FQ+rJabe60wEFdCvs039p/87LeISfOBl2hIcaCs22WTOwtcJHkCmajPCbEhSoPOoWh9dyGvK2YDbnwL2SmHb07REKRjl4VTM/39eifEb4d4DI+7nL4RbrrXjCu+HhWTeP2c6OCNa6gFOc8UUYdj+v49ytpv62+Mu1bRB8zMeWMiK9fc7pVPOV8NCfXG6cfn7uA8ypd5PzMK3qvelTF08npxG7g5/d4UyJEMohKtG5qmgtcA3Ur84yYDxpfa6MC23Sg3WFXEC4yDgA67PgOgb8US94V81fRjEYbQLPCap7J7sizWDZOuOeFXr/4d5ibzTYSlo8D/rDFI4xfd0xt4N7RM5gHmCR5gCNeKqlsnYBdZ5+AClKaZIBLTWFPN2pVJZrcubds4rXZ6wlNgz4wtcjJKC24ZdCGW1AV6vJ84yowP7PPlxUl6VORyYh6VBZ4Zc5CMJdCoockDMyWvy/KGtsXHRobg8oDTATWp+5TmTcDAGLcut8u4QhqSx0deD4p74sU40ApAkCXzi8zXO/xClSWJ9vMwWZzHfs0JeG/spHyjIyIUSlosunDsvXXxWia7Bwg5sWfGkubtYOClpbcbdSYATxfZJVWoUNT49a4HM1hWhbTW4Qwhow7ditLP0KtGGeHQZ3lxXISR7nUUJffTHIXVqkdc4lpgdNfx3iKWtK+34HC3yQufCUk1QcYSd5nPkwYxyztpkmq5muV0LTquNPImGqdumeAZmWlwmVhnNau0D2EBI28tN2Um6I3yNBtWZiU0XIbV7UZx3Oa++DlNMqJdongvoibiIyEa7ZLrg5AewvOGqp1njH0Gd+zrVnFXvBYUiqlWdxaAWf2lq34D8AxiEN3SogBboa0aR8aZ39C8cOleNfNjEVQva9kgqwtX0Q+Hxj8u8c2WlMURFyjRsFNcONR5AfwR/dM8p9q+r7W7z/nILBJUkodsbNSeKY4DJHIGkGOmrN3vmu8Za1FJ5cz7o7ds/07IzvbC9z3kQhdozALGU+p9HUQCGP5XEUsJAEd4wPTIkjapRvXdSVuKDhN44HsEvpe6mTF0F6BW+lXV8DX6ffulRJTXkkJHZKydj+eg0iDsGzudf7OkPHdCNPL64URPEyYNyIj9RrfC4MqiPMErzzMfJ+69IN4mKZSwM6zeto5ivCWL8jvOrzAZZ+SfraNmr1C6i1F6DCJkD+K+oyOIPqelagOfG13QKLo6AZeihcRL/CrPAo+EFhVCBgTpjHrzdY7c8O4h9r84MOs1p/NGvgKZZjbwW30XOQFax9lVfjzQcK2773LL5Kw/f9Q3/8qOmqMR4Pmup0xRVzlxtW7RC8TJPcnk=