steps:
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['install', 'lighthouse', 'serve']

  - name: 'debian:buster'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'apt-get update && apt-get install -y chromium'

  - name: 'node:16'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npx serve example & sleep 5'

  - name: 'node:16'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CHROME_PATH=/usr/bin/chromium; npx lighthouse --output=html --output-path=lighthouse-report.html --audit-plugins=./my-audit.cjs http://localhost:5000
   
  - name: 'node:16'
    entrypoint: 'npx'
    args:
      - '-c'
      - |
        export CHROME_PATH=/usr/bin/chromium; npx lighthouse --output=html --output-path=lighthouse-report.html --config-path=./custom-config.cjs --formFactor=desktop --screenEmulation.disabled=true ${_URL_TO_TEST}

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'lighthouse-report.html', 'gs://${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html']

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    secretEnv:
      - GITHUB_TOKEN
    args:
      - '-c'
      - |
        curl -X POST \
        -H "Authorization: token $${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${_GITHUB_REPO}/issues/${_GITHUB_PR_NUMBER}/comments" \
        -d '{"body":"Report Lighthouse: https://storage.googleapis.com/${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html"}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _URL_TO_TEST: 'http://localhost:3000'
  _GITHUB_REPO: 'gregoriopalama/alt-attr-lighthouse-audit'
  _GITHUB_PR_NUMBER: '${BUILD_NUMBER}'

secrets:
  - kmsKeyName: projects/seetheunseen/locations/global/keyRings/github-secrets/cryptoKeys/github-token
    secretEnv:
      GITHUB_TOKEN: 'CiQA7FZl4ZEjQ6qEXCD/xfgtEylkLRGYnKF4WmyQ7cJ2nxu3cjcShwEAvHKVLf1YRrG8FklT9O1YMYetM7+BTC0aSuSphwqDiK6GYzKxzxClDSUnHHzJwU0xrRl/UzwvEH31PyQZCgyBMojxQeLO2KpTJy4otKZGK2DUbgxpCscEXwADWAtwMkkxwvwVjvHcFXoGLc7ZydbknXmIXvuqV2ScI/obJwqEmTqAM0PGhAI='