steps:
  - name: 'node:22.11.0-alpine'
    args:
      - npm
      - ci
  - name: 'cypress/browsers:node-22.11.0-chrome-131.0.6778.85-1-ff-132.0.2-edge-131.0.2903.70-1'
    env:
      - LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$BRANCH_NAME
    args:
      - '-c'
      - >-
        npm install -g @lhci/cli@0.14.x && lhci autorun --failOnUploadFailure
        --config=.github/workflows/lighthouse/lighthouserc.json
        --collect.staticDistDir=example --upload.target=filesystem 
        --upload.outputDir=. --upload.reportFilenamePattern=lighthouse-report.%%EXTENSION%%
    id: lighthouse
    entrypoint: /bin/sh

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'lighthouse-report.html', 'gs://${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html']

  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - "printenv | grep BUILD_NUMBER"

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    secretEnv:
      - GITHUB_TOKEN
    args:
      - '-c'
      - >-
        curl -v -X POST 
        -H "Authorization: token $${GITHUB_TOKEN}" 
        -H "Accept: application/vnd.github.v3+json" 
        "https://api.github.com/repos/${_GITHUB_REPO}/issues/${_GITHUB_PR_NUMBER}/comments" 
        -d '{"body":"Report Lighthouse: https://storage.googleapis.com/${PROJECT_ID}-lighthouse-reports/${SHORT_SHA}/lighthouse-report.html"}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


substitutions:
  _GITHUB_REPO: 'gregoriopalama/alt-attr-lighthouse-audit'
  _GITHUB_PR_NUMBER: '${BUILD_NUMBER}'

secrets:
  - kmsKeyName: projects/seetheunseen/locations/global/keyRings/github-secrets/cryptoKeys/github-token
    secretEnv:
      GITHUB_TOKEN: 'CiQA7FZl4ZEjQ6qEXCD/xfgtEylkLRGYnKF4WmyQ7cJ2nxu3cjcShwEAvHKVLf1YRrG8FklT9O1YMYetM7+BTC0aSuSphwqDiK6GYzKxzxClDSUnHHzJwU0xrRl/UzwvEH31PyQZCgyBMojxQeLO2KpTJy4otKZGK2DUbgxpCscEXwADWAtwMkkxwvwVjvHcFXoGLc7ZydbknXmIXvuqV2ScI/obJwqEmTqAM0PGhAI='